name: Jekyll build and deploy

on:
  push:
    branches:
      - master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:    
    - name: Checkout source repository
      uses: actions/checkout@v2

    - name: Set up Node
      uses: actions/setup-node@v3
      with:
        node-version: 16.14.2
        
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7 # 3.x 로 설정시 오류 발생하여 2.7로 고정

    - name: Cache Ruby gems
      uses: actions/cache@v2
      with:
        path: vendor/bundle
        key: $-gems-$
        restore-keys: |
          $-gems-
    - name: Install dependencies
      run: |
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3
    - name: Build Jekyll site
      run: bundle exec jekyll build

    - name: Deploy to target repository
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: $ # 생성한 token 정보 설정
        publish_dir: ./_site
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'
        publish_branch: master # 대상 repository branch 정보
        external_repository: 'lahuman/lahuman.github.io' # 대상 repository
